chat_model:
  init_args:
    model: deepseek-chat
    model_provider: openai
    api_key: sk-xxxxxxxxxxxxxxx
    base_url: https://api.deepseek.com/v1
  # Rate limits for chat model API calls
  # Set to null to disable rate limiting for this service
  max_requests_per_minute: 500
  max_requests_per_day: 2000


mllm_model:
  init_args:
    model: Qwen/Qwen3-VL-32B-Instruct
    model_provider: openai
    api_key: sk-xxxxxxxxxxxxxxxx
    base_url: https://api.siliconflow.cn/v1
  # Rate limits for chat model API calls
  # Set to null to disable rate limiting for this service
  max_requests_per_minute: 500
  max_requests_per_day: 2000

image_generator:
  class_path: tools.ImageGeneratorSiliconFlowAPI
  init_args:
    api_key: sk-xxxxxxxxxxxxxxxxxxxxxx
  # Rate limits for image generation API calls
  # Set to null to disable rate limiting for this service
  max_requests_per_minute: 10
  max_requests_per_day: 500

video_generator:
  class_path: tools.VideoGeneratorVeoFastAPI
  init_args:
    api_key: xxxxxxxxxxxxxxxxxx
  # Rate limits for video generation API calls
  # Set to null to disable rate limiting for this service
  max_requests_per_minute: 2
  max_requests_per_day: 10
